spring:
  application:
    name: learner-user-api
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    #    password: Learner@2023
    #    url: jdbc:mysql://34.29.125.76:3306,34.68.236.8:3306/learnerCrownClothing?useSSL=FALSE
    password: root
    url: jdbc:mysql://35.193.120.2:3306/product_managment?useSSL=FALSE
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.73.102.15:1234/eureka/
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    password: bandi
    url: jdbc:mysql://35.193.120.2:3306/learnerCrownClothing?useSSL=FALSE
    username: bandi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.73.102.15:1234/eureka/
  instance:
    preferIpAddress: true
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    password: bandi
    url: jdbc:mysql://35.193.120.2:3306/learnerCrownClothing?useSSL=FALSE
    username: bandi
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8232
eureka:
  client:
    serviceUrl:
      defaultZone: http://34.73.102.15:1235/eureka/
  instance:
    preferIpAddress: true
